# Структуры и алгоритмы

Структуры - объекты, хранящие в себе однотипные данные. Рассмотрим некоторые из них.

## Оценка

Обычно алгоритмы оценивают по:
- памяти
- времени

Оценка по памяти заключается в ответе на вопрос, сколько нужно будет выделить памяти для решения задачи (n -> inf)

In [11]:
def bad_clear(data):
  new_data = []
  for item in data:
    if item % 2 == 0:
      new_data.append(item)

  return new_data

In [12]:
bad_clear([1,4,5,2,3,1,7,8])

[4, 2, 8]

In [ ]:
# [1 3 4 2]
# [2 3 4 1] (swapped 1 and 2)
# [2 4 3 1] (swapped 3 and 4)
# [2 4]

# [2 1 4]
# [2 4 1] (swapped 1 and 4)

# [1 2 3]
# [3 2 1] (swapped 1 and 3)
# [2 3 1] (swapped 3 and 2)

In [ ]:
def sort_func(data):
  # if len(data) == 0:
  #   return data

  # if len(data) == 1:
  #   return data

  for item in data:
    pass

  return data

In [13]:
def good_clear(data):
  i = 0
  end = len(data)

  while i < end:
    if data[i] % 2 == 0:
      i += 1
    else:
      data[i], data[end-1] = data[end-1], data[i]
      end -= 1

  return data[:end]

In [14]:
data_1 = [2,4,6,8,10,12]
print(bad_clear(data_1))
print(good_clear(data_1))

[2, 4, 6, 8, 10, 12]
[2, 4, 6, 8, 10, 12]


In [16]:
data_2 = [1,5,2,4,9,10,2,8,1]
print(bad_clear(data_2))
print(good_clear(data_2))

[2, 4, 10, 2, 8]
[8, 2, 2, 4, 10]


In [15]:
data_3 = [1,5,7,11,5,7,21]
print(bad_clear(data_3))
print(good_clear(data_3))

[]
[]


Оценка по времени заключается в ответе на вопрос, сколько времени займет решение проблемы (n -> inf)

In [18]:
def bubble_sort(data):
  for i in range(len(data)):
    for j in range(len(data)-i-1):
      if data[j] > data[j+1]:
        data[j], data[j+1] = data[j+1], data[j]

In [ ]:
# [5 3 1 6]
# [3 5 1 6]
# [3 1 5 6]
# [3 1 5 6]
# [1 3 5 6]
# [1 3 5 6]
# [1 3 5 6]

# [5 4 3 2]
# [4 5 3 2]
# [4 3 5 2]
# [4 3 2 5]
# [3 4 2 5]
# [3 2 4 5]
# [2 3 4 5]

In [19]:
data = [1,3,67,21,3,45,1]
bubble_sort(data)
print(data)

[1, 1, 3, 3, 21, 45, 67]


In [20]:
def radix_sort(data):
  colours = {"red": 0, "orange": 0, "yellow": 0, "green": 0, "light-blue": 0, "blue": 0, "purple": 0}

  for item in data:
    colours[item] += 1

  res = []
  for k, v in colours.items():
    for i in range(v):
      res.append(k)

  return res

In [21]:
data = ["red", "blue", "blue", "yellow", "green"]
print(radix_sort(data))

['red', 'yellow', 'green', 'blue', 'blue']


https://www.youtube.com/watch?v=BeoCbJPuvSE

https://leetcode.com/problemset/all/?sorting=W3sic29ydE9yZGVyIjoiQVNDRU5ESU5HIiwib3JkZXJCeSI6IkRJRkZJQ1VMVFkifV0%3D

https://www.codewars.com/

## Стеки (LIFO)

In [ ]:
# 1
# 1 2
# 1 2 3
# 1 2 -> 3

# last in - first out

In [22]:
class Stack():
  def __init__(self):
    self.values = []

  def put(self, value):
    self.values.append(value)

  def pop(self):
    print(self.values[len(self.values)-1])
    self.values = self.values[:len(self.values)-1]

In [23]:
s = Stack()
s.put(3)
s.put(5)
s.put(7)
s.pop()
s.pop()
s.pop()

7
5
3


In [ ]:
# main -> func -> sub_func
# main
# main func
# main func sub_func
# main func
# main

## Очереди (FIFO)

In [ ]:
# 1
# 1 2
# 1 2 3
# 2 3 -> 1

# first in - first out

In [24]:
class Queue():
  def __init__(self):
    self.values = []

  def put(self, value):
    self.values.append(value)

  def pop(self):
    print(self.values[0])
    self.values = self.values[1:]

In [25]:
q = Queue()
q.put(3)
q.put(5)
q.put(7)
q.pop()
q.pop()
q.pop()

3
5
7


In [28]:
# main service (download []data) - 1s
# handler service - 5s
# queue service (Kafka, RabbitMQ)

# main -> queue -> handler
# m1
#        [m1]
# m2     [ ]         m1
#        [m2]        m1
# m3     [m2]        m1
#        [m2, m3]    m1
# m4     [m2, m3]    m1
#        [m3, m4]    m2

## Списки

In [ ]:
# elem1 -> elem2 -> elem3

# elem1 -> elem2 -> elem3
#       <-       <-

Списки бывают односвязные (самые простые) и двусвязные.

In [29]:
class LinkedList():
  def __init__(self, value):
    self.value = value
    self.next = None

  def bind_next(self, other):
    self.next = other

  def print_all(self):
    curr_node = self
    vals = []
    while curr_node:
      vals.append(curr_node.value)
      curr_node = curr_node.next
    print(vals)

  def add_node(self, value, other):
    # a -> b -> d
    # next = d (next_node = curr_node.next)
    # a -> b -> c (curr_node.next = other)
    # c.next = d (other.next = next_node)
    # a -> b -> c -> d

    curr_node = self

    while curr_node:
      if curr_node.value == value:
        next_node = curr_node.next
        curr_node.next = other
        other.next = next_node
        return

      curr_node = curr_node.next

  def delete_node(self, value):
    # a -> b -> d
    # parent = a
    # next = d
    # a
    # parent.next = d
    # a -> d

    curr_node = self

    parent = None

    while curr_node:
      if curr_node.value == value:
        if parent:
          parent.next = curr_node.next
          return self
        else:
          return self.next

      parent = curr_node
      curr_node = curr_node.next

In [30]:
ll_1 = LinkedList(0)
ll_2 = LinkedList(1)
ll_3 = LinkedList(2)
ll_4 = LinkedList(3)

ll_1.bind_next(ll_2)
ll_2.bind_next(ll_3)
ll_3.bind_next(ll_4)

In [31]:
ll_1.print_all()

[0, 1, 2, 3]


In [32]:
ll_3.print_all()

[2, 3]


In [33]:
l0 = LinkedList(0)
l1 = LinkedList(1)
l2 = LinkedList(2)
l3 = LinkedList(3)

l0.bind_next(l1)
l1.bind_next(l2)

l0.print_all()

[0, 1, 2]


In [34]:
l0.add_node(2, l3)

l0.print_all()

[0, 1, 2, 3]


In [36]:
l0 = LinkedList(0)
l1 = LinkedList(1)
l2 = LinkedList(2)

l0.bind_next(l1)
l1.bind_next(l2)

l0.print_all()

l0.delete_node(1).print_all()

[0, 1, 2]
[0, 2]


In [37]:
class DoubleLinkedList():
  def __init__(self, value):
    self.value = value
    self.next = None
    self.prev = None

  def bind_next(self, other):
    # a b
    # a -> b
    # b <- a
    self.next = other
    other.prev = self

In [38]:
dll_1 = DoubleLinkedList(0)
dll_2 = DoubleLinkedList(1)
dll_3 = DoubleLinkedList(2)

dll_1.bind_next(dll_2)
dll_2.bind_next(dll_3)

print(dll_1.value, dll_1.next.value, dll_1.next.next.value)
print(dll_3.value, dll_3.prev.value, dll_3.prev.prev.value)

0 1 2
2 1 0


Какие операции можно провернуть со списками? Можно добавлять элемент, удалять элемент, находить элемент и т.д.

## Деревья

In [ ]:
data = [2, 4, 1, 3, 6]

min = data[0]
for item in data:
  if min > item:
    min = item

#         2
#      1     4
#           3  6

In [40]:
class BinaryTreeNode():
  def __init__(self, value):
    self.l = None
    self.r = None
    self.value = value

  def print(self):
    print(self.value)
    if self.l:
      print("left for", self.value)
      self.l.print()
    if self.r:
      print("right for", self.value)
      self.r.print()

class BinaryTree():
  def __init__(self):
    self.root = None

  def add(self, value):
    if not self.root:
        self.root = BinaryTreeNode(value)
        return

    def _add(node, value):
      if node.value > value:
        if node.l:
          _add(node.l, value)
        else:
          node.l = BinaryTreeNode(value)
      else:
        if node.r:
          _add(node.r, value)
        else:
          node.r = BinaryTreeNode(value)

    _add(self.root, value)

  def print_all(self):
    self.root.print()

In [41]:
t = BinaryTree()
t.add(5)
t.add(4)
t.add(1)
t.add(8)
t.add(6)
t.add(9)

In [42]:
t.print_all()

5
left for 5
4
left for 4
1
right for 5
8
left for 8
6
right for 8
9


In [43]:
#             5
#         4      8
#      1    6   7  9

In [44]:
#            1
#              2
#               3
#                4

image.png image.png

# Паттерны

Паттерн, в общем то, представляет из себя некую конструкцию, которую удобно переиспользовать из раза в раз на разных проектах (так, некоторые паттерны включены изначально в языках)

https://refactoring.guru/design-patterns/python

## Синглтон

In [ ]:
logger = None

def new_logger():
  path = "logs.txt"
  f = open(path, "w")
  return f

def create_logger():
  if logger:
    return logger
  logger = new_logger()
  return logger

In [45]:
class Logger():
  def __new__(cls, *args, **kwargs):
    if not hasattr(cls, '_logger'):
        cls._logger = super(Logger, cls).__new__(cls, *args, **kwargs)
    # Возвращаем созданный (только что или ранее) объект.
    return cls._logger

  def __init__(self):
    pass

In [46]:
l = Logger()
l2 = Logger()
print(l is l2)

True


## Адаптер

In [47]:
class ForeignRunner():
  def foreign_run(self):
    return "gninnur"

  def other(self):
    print("i'm an alien")

class MyRunner():
  def run(self):
    return "running"

  def other(self):
    print("hi!")

class Adapter(MyRunner, ForeignRunner):
  def run(self):
    return self.foreign_run()[::-1]

In [48]:
mr = MyRunner()
mr.run()

'running'

In [49]:
fr = ForeignRunner()
fr.foreign_run()

'gninnur'

In [50]:
ar = Adapter()
ar.run()

'running'

In [51]:
Adapter().other()

hi!


## Наблюдатель

In [52]:
class Child():
  def __init__(self, name):
    self.name = name
    self.state = "calm"
    self.observers = []

  def do_smth_good(self):
    print("doing smth")
    self.state = "calm"
    for o in self.observers:
      o.check_state()

  def do_smth_bad(self):
    print("doing smth bad")
    self.state = "not calm"
    for o in self.observers:
      o.check_state()

class Parent():
  def __init__(self):
    self.observant = None

  def look_at(self, child):
    self.observant = child
    child.observers.append(self)

  def check_state(self):
    print(self.observant.state)
    if self.observant.state == "not calm":
      print(self.observant.name.upper())
      self.observant.state = "calm"


In [53]:
c = Child("Alice")
p1 = Parent()
p2 = Parent()
p1.look_at(c)
p2.look_at(c)

In [54]:
c.do_smth_bad()

doing smth bad
not calm
ALICE
calm


In [55]:
actions = [0,0,0,1,0,1,1,0]
for a in actions:
  if a == 0:
    c.do_smth_good()
  else:
    c.do_smth_bad()

doing smth
calm
calm
doing smth
calm
calm
doing smth
calm
calm
doing smth bad
not calm
ALICE
calm
doing smth
calm
calm
doing smth bad
not calm
ALICE
calm
doing smth bad
not calm
ALICE
calm
doing smth
calm
calm


# Мини домашка

## Задание 1

In [39]:
#  elem1 - > elem2 -> elem3 -> elem4
#             ^                   |
#             |                   |
#              -------------------

# 1 цикл (шаг 1)
# elem1 elem2 elem3 elem4 elem2 elem3 ...
# 2 цикл (шаг 2)
# elem2 elem4 elem3

Хотим найти цикл в односвязном списке; если он есть - возвращаем True, если нет - False
При этом нам нельзя сохранять список уже посещенных нод, хотим сделать проверку в формате, который обсуждали на лекции (идти с разным шагом)

In [ ]:
def find_cycle(node):
  pass

In [ ]:
ll_1 = LinkedList(0)
ll_2 = LinkedList(1)
ll_3 = LinkedList(2)
ll_4 = LinkedList(3)

ll_1.bind_next(ll_2)
ll_2.bind_next(ll_3)
ll_3.bind_next(ll_4)

assert find_cycle(ll_1) == False

ll_4.bind_next(ll_2)

assert find_cycle(ll_1) == True

## Задание 2

Напишите класс ConnectToDB так, чтобы при передаче уже однажды переданных параметров возвращался созданный ранее экземпляр класса, при новых - новый

In [ ]:
class ConnectToDB():
  connections = {}

  def __new__(cls, *args, **kwargs):
    pass

  def __init__(self, address=""):
    self.address = address

In [ ]:
c1 = ConnectToDB(address="addr1")
c2 = ConnectToDB(address="addr1")
c3 = ConnectToDB(address="addr2")
assert c1 is c2
assert c1 is not c3